name: DeathQuestion
version: ${project.version}
main: net.kunmc.lab.deathquestion.DeathQuestion
api-version: 1.16
commands:
  open:
    permission: deathQuestion.op
  vote:
    permission: deathQuestion.public
  question:
    permission: deathQuestion.op
permissions:
  deathQuestion.public:
    default: true
  deathQuestion.op:
    default: op